### ISSUE TITLE
LookupTable has no field 'dim_10' among its fields:

### ISSUE THREAD

**Issue by nischalpatil** [CSTR-Edinburgh/Ossian#11]
I am truing to train on hindi language. I followed the same exact steps mentioned in the document. What is it that i am missing. If you can please provide a step by step guide to train this for Hindi language.
I tested the same for English voice and it runs perfectly.

this is the whole error:
== Train voice (proc no. 3 (word_vector_tagger))  ==
          Applying processor word_vector_tagger
p
Traceback (most recent call last):
  File "./scripts/train.py", line 147, in <module>
    main_work()
  File "./scripts/train.py", line 82, in main_work
    train(opts, dirs)
  File "./scripts/train.py", line 121, in train
    voice.train(corpus)
  File "/home/nyg/Ossian/scripts/main/Voice.py", line 363, in train
    processor.apply_to_utt(utterance, voice_mode=self.run_mode)
  File "/home/nyg/Ossian/recipes/../scripts/processors/UtteranceProcessor.py", line 222, in apply_to_utt
    self.process_utterance(utterance)
  File "/home/nyg/Ossian/recipes/../scripts/processors/VSMTagger.py", line 76, in process_utterance
    kwargs={"field": "dim_%s"%(i)}) 
  File "/home/nyg/Ossian/scripts/util/NodeProcessors.py", line 34, in enrich_nodes
    transformed_data = function(input_data, **kwargs)
  File "/home/nyg/Ossian/scripts/util/LookupTable.py", line 85, in lookup
    assert field in self.fields,"LookupTable has no field '%s' among its fields: %s"%(field, " ".join(self.fields))
AssertionError: LookupTable has no field 'dim_10' among its fields: dim_1 dim_2 dim_3 dim_4 dim_5 dim_6 dim_7 dim_8 dim_9

**Comment by nischalpatil** [comment]
This issue is opened since 10 days still no help...

**Comment by f-e-l-i-x** [comment]
I got the same problem with German, now I removed all non-standard letters from the text corpus, i.e., ÄÖÜäöüß,.!?
I also changed the name of the speaker from test_de to testde without underscore

Now it works
