### ISSUE TITLE
can't run the demo

### ISSUE THREAD

**Issue by yfliao** [CSTR-Edinburgh/Ossian#15]
Dear all,

I have successfully executed the setup script:
./scripts/setup_tools.sh

and prepared the training data:
./corpus/rm/speakers/rss_toy_demo/
./corpus/rm/text_corpora/wikipedia_10K_words/

But I can't run the demo. Here is the output:
> python ./scripts/train.py -s rss_toy_demo -l rm -p 1 naive_01_nn
> /home/liao/Ossian/
> -- Gather corpus
> -- Train voice
> /home/liao/Ossian/train//rm/speakers/rss_toy_demo/naive_01_nn
> /home/liao/Ossian/voices//rm/rss_toy_demo/naive_01_nn
> try loading config from python...
> /home/liao/Ossian/recipes/naive_01_nn.cfg
> trouble importting from merlin -- installed properly?

Another thing is there is a bug in "tools/g2p/Utility.cc" while running test_release.sh

> Utility.cc: In function ‘int Core::getline(std::istream&, std::__cxx11::string&, std::__cxx11::string)’:
> Utility.cc:43:21: error: ‘EOF’ was not declared in this scope
>     if (is.get() == EOF) return EOF;
>                     ^
> Utility.cc:48:35: error: ‘EOF’ was not declared in this scope
>     while (((token = is.get()) != EOF) &&
>                                   ^
> error: command 'g++' failed with exit status 1
> rm: cannot remove './train/en/speakers/tundra_toy_demo/*': No such file or directory
> rm: cannot remove 'voices/en/tundra_toy_demo/english_gold_basic': No such file or directory
> -- Gather corpus
> Traceback (most recent call last):
>  File "./scripts/train.py", line 147, in <module>
>    main_work()
>  File "./scripts/train.py", line 82, in main_work
>    train(opts, dirs)
>  File "./scripts/train.py", line 111, in train
>    for f in os.listdir(c):
> OSError: [Errno 2] No such file or directory: 
> '/home/liao/Ossian/corpus/en/speakers/tundra_toy_demo/txt'
> /home/liao/Ossian/train//en/speakers/tundra_toy_demo/english_gold_basic
> /home/liao/Ossian/voices//en/tundra_toy_demo/english_gold_basic
> No voice of specified configuration exists to synthesise from

Could you give me some tips?

Thanks a lot!

Best Regards,
Yuanfu

**Comment by nischalpatil** [comment]
make sure you install merlin properly first.

**Comment by maxmln** [comment]
Hey, has this been solved? I am having the same issue.
