### ISSUE TITLE
problem when training

### ISSUE THREAD

**Issue by LionnelBall** [CSTR-Edinburgh/Ossian#26]
when training the demo, I encountered this problem:

== Train voice (proc no. 1 (word_splitter))  ==
<Tokenisers.RegexTokeniser object at 0x7f6bc78bc400>
['__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'add_safetext', 'add_terminal_tokens', 'add_token_classes', 'apply_to_utt', 'apply_to_utts_which_have', 'child_node_type', 'class_attribute', 'class_patterns', 'classify_token', 'component_path', 'default_class', 'do_training', 'get_location', 'get_training_dir', 'language', 'lowercase_safetext', 'parallelisable', 'process_utterance', 'processor_name', 'regex', 'reuse_component', 'safetext_attribute', 'safetext_token', 'split_attribute', 'split_pattern', 'splitting_function', 'target_nodes', 'train', 'train_on_utts_which_have', 'trained', 'verify', 'voice_resources']
<class 'Tokenisers.RegexTokeniser'>
False
Train processor word_splitter
RegexTokeniser requires no training
Applying processor word_splitter
ppppppppppppppppppppppppppppp

== Train voice (proc no. 2 (segment_adder))  ==
<Phonetisers.NaivePhonetiser object at 0x7f6bc78bc8d0>
['__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'apply_to_utt', 'apply_to_utts_which_have', 'child_node_type', 'class_attribute', 'component_path', 'do_training', 'get_location', 'get_phonetic_segments', 'get_training_dir', 'language', 'output_attribute', 'parallelisable', 'possible_pause_classes', 'probable_pause_classes', 'process_utterance', 'processor_name', 'reuse_component', 'target_attribute', 'target_nodes', 'train', 'train_on_utts_which_have', 'trained', 'verify', 'voice_resources', 'word_classes']
<class 'Phonetisers.NaivePhonetiser'>
False
Train processor segment_adder
NaivePhonetiser requires no training
Applying processor segment_adder
uuuuuuuuuuuuuuuuuuuuuuuuuuuuu

== Train voice (proc no. 3 (word_vector_tagger))  ==
<VSMTagger.VSMTagger object at 0x7f6bc78bc3c8>
['__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_process_text_line', 'apply_to_utt', 'apply_to_utts_which_have', 'component_path', 'context_size', 'discretisation_method', 'do_training', 'get_location', 'get_training_dir', 'input_attribute', 'language', 'n_discretisation_bins', 'norm_counts', 'output_attribute_stem', 'parallelisable', 'process_utterance', 'processor_name', 'rank', 'replace_whitespace', 'reuse_component', 'svd_algorithm', 'table_file', 'target_nodes', 'tokenisation_pattern', 'train', 'train_on_utts_which_have', 'trained', 'unseen_method', 'verify', 'voice_resources', 'vsm']
<class 'VSMTagger.VSMTagger'>
True
Applying processor word_vector_tagger
p<Utterance.Utterance object at 0x7f6d0904b588>
//token[@token_class='word']
[]
Traceback (most recent call last):
  File "./scripts/train.py", line 148, in <module>
    main_work()
  File "./scripts/train.py", line 83, in main_work
    train(opts, dirs)
  File "./scripts/train.py", line 122, in train
    voice.train(corpus)
  File "/home/chenliang/1_code/2_TTS/Ossian/scripts/main/Voice.py", line 378, in train
    processor.apply_to_utt(utterance, voice_mode=self.run_mode)
  File "/home/chenliang/1_code/2_TTS/Ossian/scripts/processors/UtteranceProcessor.py", line 222, in apply_to_utt
    self.process_utterance(utterance)
  File "/home/chenliang/1_code/2_TTS/Ossian/scripts/processors/VSMTagger.py", line 76, in process_utterance
    kwargs={"field": "dim_%s"%(i)})
  File "/home/chenliang/1_code/2_TTS/Ossian/scripts/util/NodeProcessors.py", line 35, in enrich_nodes
    assert len(nodes) > 0
AssertionError

Does anyone know why this happend? How to solve it? Thank you for helping.

**Comment by A-d-DASARE** [comment]
Did you get help? I am also facing same error. For one data set it works. For other it throws up error.
